default: true
blanks-around-lists: false
line-length: false
no-inline-html: false
no-bare-urls: false
no-emphasis-as-heading: false
no-multiple-blanks: false
no-trailing-punctuation: false
no-duplicate-heading:
  siblings_only: true
  allow_different_nesting: true
heading-increment: false
heading-style:
  style: atx
emphasis-style:
  style: asterisk
strong-style:
  style: asterisk
ol-prefix:
  style: one
ul-indent: false
ul-style:
  style: dash
fix: false
table-column-count: false
table-pipe-style: false
