- name: Quarterly Engineering satisfaction survey NPS score
  base_path: "/handbook/engineering/infrastructure/engineering-productivity/space/"
  definition: Test description
  target: equal or greater than 99.80%
  category: satisfaction
  dri: <a href="https://gitlab.com/meks">Mek Stittri</a>
  health:
    level: 3
    reasons:
      - April 2024 Availability 99.95%
      - March 2024 Availability 100.00%
  tableau_data:
    charts:
      - url: https://us-west-2b.online.tableau.com/t/gitlabpublic/views/InfrastructureKPIs/GitlabAvailabilitySLO
        height: 400px
        toolbar: hidden
        hide_tabs: true
  urls:
    - https://about.gitlab.com/handbook/engineering/monitoring/#historical-service-availability
    - https://dashboards.gitlab.net/d/general-slas/general-slas?orgId=1&from=now%2FM&to=now
- name: Team member retention
  base_path: "/handbook/engineering/infrastructure/engineering-productivity/space/"
  definition: Test description
  target: equal or greater than 99.80%
  category: satisfaction
  dri: <a href="https://gitlab.com/meks">Mek Stittri</a>
  health:
    level: 3
    reasons:
      - April 2024 Availability 99.95%
      - March 2024 Availability 100.00%
  tableau_data:
    charts:
      - url: https://us-west-2b.online.tableau.com/t/gitlabpublic/views/InfrastructureKPIs/GitlabAvailabilitySLO
        height: 400px
        toolbar: hidden
        hide_tabs: true
  urls:
    - https://about.gitlab.com/handbook/engineering/monitoring/#historical-service-availability
    - https://dashboards.gitlab.net/d/general-slas/general-slas?orgId=1&from=now%2FM&to=now
